# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: madhupdocker-app
  namespace: madhu
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]